name: CI-test

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies for Javascript-implementation
        run: |
          cd javascript-implementation
          npm install

      - name: Run tests for Javascript-implementation
        run: |
          cd javascript-implementation
          npm run test

      - name: Install dependencies for typescript-implementation
        run: |
          cd typescript-implementation
          npm install

      - name: Run tests for typescript-implementation
        run: |
          cd typescript-implementation
          npm run test
